"""AI generation endpoints — concepts use Claude, others are mock stubs."""

import random
import uuid

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.project import GameConcept
from app.schemas.project import (
    GameConceptOut,
    GenerateCardsRequest,
    GenerateConceptsRequest,
    RunSimulationRequest,
)
from app.services.concept_generator import generate_concepts as generate_concepts_service

router = APIRouter(prefix="/generate", tags=["generate"])


@router.post("/{project_id}/concepts", response_model=list[GameConceptOut])
async def generate_concepts(
    project_id: str,
    data: GenerateConceptsRequest,
    db: AsyncSession = Depends(get_db),
):
    """Generate game concept suggestions from a natural language brief.

    Uses Claude API if ANTHROPIC_API_KEY is set, otherwise returns mock data.
    Persists generated concepts to the database.
    """
    results = await generate_concepts_service(
        brief=data.brief,
        brief_settings=data.brief_settings,
        count=data.count,
    )

    # Persist to database
    for concept_out in results:
        db_concept = GameConcept(
            id=concept_out.id,
            project_id=project_id,
            title=concept_out.title,
            description=concept_out.description,
            mechanics=concept_out.mechanics,
            comparable_games=concept_out.comparable_games,
            score=concept_out.score,
        )
        db.add(db_concept)
    await db.commit()

    return results


@router.post("/{project_id}/cards")
async def generate_cards(
    project_id: str,
    data: GenerateCardsRequest,
    db: AsyncSession = Depends(get_db),
):
    """Generate individual card instances for a card type.

    TODO: Replace with Claude API call to generate thematic card text, stats, effects.
    """
    cards = []
    for i in range(data.count):
        cards.append({
            "id": str(uuid.uuid4()),
            "type_id": data.card_type_id,
            "name": f"Generated Card {i + 1}",
            "cost": random.randint(0, 5),
            "stats": {"Power": random.randint(1, 6), "Defense": random.randint(1, 6)},
            "effect": "Placeholder effect — will be generated by AI.",
            "flavor_text": "Placeholder flavor text.",
            "art_url": None,
        })
    return cards


@router.post("/{project_id}/simulate")
async def run_simulation(
    project_id: str,
    data: RunSimulationRequest,
):
    """Run Monte Carlo balance simulation.

    TODO: Replace with actual game state machine + random playout engine.
    """
    player_count = 4
    win_rates = [
        {"position": f"P{i + 1}", "rate": round(random.gauss(50, 5), 1)}
        for i in range(player_count)
    ]

    usage = [
        {"name": "Artifacts", "value": round(random.uniform(40, 70))},
        {"name": "Creatures", "value": round(random.uniform(15, 35))},
        {"name": "Events", "value": round(random.uniform(5, 20))},
    ]

    length = [
        {"minutes": m, "frequency": max(0, round(random.gauss(30 if m == 45 else 10, 8)))}
        for m in range(30, 75, 5)
    ]

    comeback = [
        {"turn": t, "rate": max(0, round(random.gauss(30, 12)))}
        for t in range(3, 15, 2)
    ]

    return {
        "winRate": win_rates,
        "usage": usage,
        "length": length,
        "comeback": comeback,
        "gamesPlayed": data.game_count,
    }
