"""AI generation endpoints — currently return mock data, ready for real AI integration."""

import random
import uuid

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.project import GameConcept
from app.schemas.project import (
    GameConceptOut,
    GenerateCardsRequest,
    GenerateConceptsRequest,
    RunSimulationRequest,
)

router = APIRouter(prefix="/generate", tags=["generate"])

# Mechanic pools for mock generation
MECHANICS = [
    "Hand Management", "Deck Building", "Worker Placement", "Area Control",
    "Push Your Luck", "Cooperative", "Engine Building", "Drafting",
    "Set Collection", "Trick-Taking", "Tableau Building", "Resource Management",
    "Action Points", "Dice Rolling", "Tile Placement", "Route Building",
]

COMPARABLE_GAMES = [
    "Pandemic", "Gloomhaven", "Terraforming Mars", "Wingspan", "Arkham Horror",
    "Spirit Island", "7 Wonders", "Dominion", "Azul", "Catan", "Root",
    "Everdell", "The Crew", "Arcs", "Brass: Birmingham",
]


@router.post("/{project_id}/concepts", response_model=list[GameConceptOut])
async def generate_concepts(
    project_id: str,
    data: GenerateConceptsRequest,
    db: AsyncSession = Depends(get_db),
):
    """Generate game concept suggestions from a natural language brief.

    TODO: Replace mock logic with Claude API call using structured output.
    """
    concepts = []
    for i in range(data.count):
        mechanics = random.sample(MECHANICS, k=3)
        comparables = random.sample(COMPARABLE_GAMES, k=2)
        concept = GameConcept(
            id=str(uuid.uuid4()),
            project_id=project_id,
            title=f"Concept {i + 1}: {data.brief_settings.theme}",
            description=f"An AI-generated concept based on: {data.brief[:100]}",
            mechanics=mechanics,
            comparable_games=comparables,
            score=round(random.uniform(70, 98), 1),
        )
        db.add(concept)
        concepts.append(concept)
    await db.commit()
    return concepts


@router.post("/{project_id}/cards")
async def generate_cards(
    project_id: str,
    data: GenerateCardsRequest,
    db: AsyncSession = Depends(get_db),
):
    """Generate individual card instances for a card type.

    TODO: Replace with Claude API call to generate thematic card text, stats, effects.
    """
    cards = []
    for i in range(data.count):
        cards.append({
            "id": str(uuid.uuid4()),
            "type_id": data.card_type_id,
            "name": f"Generated Card {i + 1}",
            "cost": random.randint(0, 5),
            "stats": {"Power": random.randint(1, 6), "Defense": random.randint(1, 6)},
            "effect": "Placeholder effect — will be generated by AI.",
            "flavor_text": "Placeholder flavor text.",
            "art_url": None,
        })
    return cards


@router.post("/{project_id}/simulate")
async def run_simulation(
    project_id: str,
    data: RunSimulationRequest,
):
    """Run Monte Carlo balance simulation.

    TODO: Replace with actual game state machine + random playout engine.
    """
    player_count = 4
    win_rates = [
        {"position": f"P{i + 1}", "rate": round(random.gauss(50, 5), 1)}
        for i in range(player_count)
    ]

    usage = [
        {"name": "Artifacts", "value": round(random.uniform(40, 70))},
        {"name": "Creatures", "value": round(random.uniform(15, 35))},
        {"name": "Events", "value": round(random.uniform(5, 20))},
    ]

    length = [
        {"minutes": m, "frequency": max(0, round(random.gauss(30 if m == 45 else 10, 8)))}
        for m in range(30, 75, 5)
    ]

    comeback = [
        {"turn": t, "rate": max(0, round(random.gauss(30, 12)))}
        for t in range(3, 15, 2)
    ]

    return {
        "winRate": win_rates,
        "usage": usage,
        "length": length,
        "comeback": comeback,
        "gamesPlayed": data.game_count,
    }
